### ISSUE TITLE
Version Check From Store

### ISSUE THREAD

**Issue by olawalejuwonm** [tessus/react-native-version-info#13]
Can this library be used to get the latest app version by parsing google play store, apple app store's app information?

**Comment by tessus** [comment]
Maybe. As the docs state this module reads the native manifest to retrieve the info. Thus if the store version is the same as the manifest, then yes. (I highly suspect that this is the case. Stores read the manifest as well.)

This module does not read any information from a store.

**Comment by olawalejuwonm** [comment]
If yes how can it be set up?

**Comment by tessus** [comment]
I don't understand. You follow the steps in the [README.md](https://github.com/tessus/react-native-version-info/blob/master/README.md)

**Comment by SufianBabri** [comment]
I believe what you were looking for was either [react-native-version-check](https://github.com/kimxogus/react-native-version-check) or [react-native-store-version](https://github.com/watanabeyu/react-native-store-version). These libraries can fetch the latest version available on the store.
