### ISSUE TITLE
Automatic linking not working for ios

### ISSUE THREAD

**Issue by ahmetacikgoz** [tessus/react-native-version-info#3]
`react-native link react-native-version-info` command not working for ios. 
Manuel linking is working.

React Native Version: "0.54.2"

**Comment by ahmetacikgoz** [comment]
Sorry for unclear issue. I was expecting `react-native link` will add Library to app like in the android platform. But i saw a new line in Podfile later.

**Comment by tessus** [comment]
I've read in the [react-native documentation](https://facebook.github.io/react-native/docs/linking-libraries-ios) the following:

_Note: If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link library using Podfile._

But if your project is not using CocoaPods, it looks like a bug upstream. It should only use podfiles, if 2 conditions are met: the project uses cocoapds (your code) AND a podfile exists in the react-native module (my code).

**Comment by tessus** [comment]
Just wanted to follow up. What's the current status?

**Comment by tessus** [comment]
Closing this for now. Please reopen, if it has not been resolved.

**Comment by gauthampait** [comment]
Still an issue. It return undefined on iOS with react-native link. Worked fine on Android though.
